#!/bin/bash

rm -Rf Build
mkdir Build
cd Build
cmake .. -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix`;
make;
su -c "make install";
kbuildsycoca4;
kquitapp plasma-desktop;
sleep 2s;
plasma-desktop 1>/dev/null 2>/dev/null;
